# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kachlan < Formula
  desc "Fast video compression powered by ffmpeg"
  homepage "https://github.com/kmtusher97/kachlan"
  version "0.5.1"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kmtusher97/kachlan/releases/download/v0.5.1/kachlan_darwin_amd64.tar.gz"
      sha256 "9d7a02186e94f1c1cde830c296197b27808f76097d4352df29afd41045ae0b72"

      define_method(:install) do
        bin.install "kachlan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kmtusher97/kachlan/releases/download/v0.5.1/kachlan_darwin_arm64.tar.gz"
      sha256 "e3a37093a1081b2a6a5942aa593bbf771815c03732c56829539f519fba752ad3"

      define_method(:install) do
        bin.install "kachlan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kmtusher97/kachlan/releases/download/v0.5.1/kachlan_linux_amd64.tar.gz"
      sha256 "708e65cc502e907d7ade9255d256b3daadd3c8fd0695fc9492662ba978e006c2"
      define_method(:install) do
        bin.install "kachlan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kmtusher97/kachlan/releases/download/v0.5.1/kachlan_linux_arm64.tar.gz"
      sha256 "4c60f3670f9588af3872d1c33b9d1906259e3bb8d25faced7b4917949cdba785"
      define_method(:install) do
        bin.install "kachlan"
      end
    end
  end
end
